site_name: aerobless.github.io
site_author: Theo Winter
site_url: https://aerobless.github.io

repo_name: aerobless.github.io
repo_url: https://github.com/aerobless/aerobless.github.io

theme:
  name: material
  language: en
#  logo: './logo.svg'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aerobless
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/TheodorWinter

google_analytics:
  - UA-90728111-4
  - auto

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true